inherit_from: .rubocop_todo.yml

AllCops:
  EnabledByDefault: false
  AutoCorrect: true
  NewCops: enable

Layout/IndentationConsistency:
  AutoCorrect: true

Style/Documentation:
  Enabled: false
  AutoCorrect: false

Style/BlockComments:
  Enabled: false

Metrics/MethodLength:
  AutoCorrect: false
  Enabled: false
  Max: 1000

Metrics/AbcSize
  Enabled: false